### ISSUE TITLE
What is this library for?

### ISSUE THREAD

**Issue by KOLANICH** [thombashi/mbstrdecoder#1]
Doesn't python support multibyte codepages out of the box?

**Comment by thombashi** [comment]
Hi,

This library aims to automatically detect codecs of encoded bytes, and decode to Unicode strings.

As far as I know, Python standard library does not have that capability.
Decoding encoded bytes when the codec is unknown would be painful.
Sometimes I encountered this kind of situations.
So that's why I made the library.

Does it make sense to you?

**Comment by KOLANICH** [comment]
>Decoding encoded bytes when the codec is unknown would be painful.

But what's wrong with 
```python
encoded_multibyte_text.decode(chardet.detect(encoded_multibyte_text)['encoding'])
```
?

The problem with this lib is that it is an additional dependency I have to audit before using some of your packages.

**Comment by KOLANICH** [comment]
The dependency on chardet is not a problem. The problem is dependency of external packages on mbstrdecoder. I had to audit it before installation.

Should the functionality of this lib be part of chardet?

**Comment by thombashi** [comment]
Now, I think I understand your problem.
However, the author of `chardet` would probably not accept that change because of `chardet` and `mbstrdecoder` very different approach.
`mbstrdecoder` take kind of brute force approach.

**Comment by KOLANICH** [comment]
Could you, please, make this lib optinal for all your libs using it?

**Comment by thombashi** [comment]
I would like to help you, but I would rather not make it optional.
This library makes me easy to support multi-byte characters, and make it optional would cause inconvenience for some users.
Furthermore, I used several libraries for `pytablewriter` made by myself aside from `mbstrdecoder`, some of these libraries are mandatory.

I am not sure what you need to do audit a library though, is it so hard?

**Comment by KOLANICH** [comment]
>I am not sure what you need to do audit a library though, is it so hard?

The problem is that dependencies are updated and each update can bring malicious code. There were multiple cases of inserting malware into dependencies updates, especially in Node.js ecosystem where dependency trees are especially large and hard to audit. Sometimes repos were bought from its owner (and these owners after the fact of using their lib for spreading malware was discovered, said that they would like to do it again if they could because the compensation was large enough), sometimes the owner has lost interest in maintaining his lib and has transfered it to a new maintainer, than the new maintainer has inserted there a backdoor and have stolen some cryptocurrency.

Or your account can be hacked in order to pland a backdoor, but I have not yet heard about this happenning in real life.

That's why everyone should understand that introducing a dependency is trading some security for collaboration.

<details><summary>I have some ideas how to fix that</summary>(permission system for packages + bidirectional taint checking + Bell-Lapadula model, but it needs explicitly fixing security contexts in order to be useful, and if I have this operation in a program or its dependency (and we definitely need this operations, otherwise one cannot write even a simple app interacting to a remote web server, since it leaks some info and even a human cannot correctly understand if this info really deserves the taint it has), I cannot prove security of the application anymore).</details>

So for now one should try to make as many dependencies optional as possible and to make as many people as possible to be involved into source code editing, so if you have lost interest, the community can continue maintaining, not a guy spreading malware. And if someone hacked your acc and planted a backdoor, people subscribed to the repo and involved into the code would spot that (though there is a way to make people notice only after some time: banning everyone subscribed to a repo and to your acc, this would cause them be unsubscribed without any notice, then unbanning them to make them not to suspicious about them unable to create an issue).

**Comment by thombashi** [comment]
I know the incident of `flatmap-stream`. I agree with optional dependencies would be preferable for security reasons, and I try to make dependencies optional with my projects I far as I can.
However, I would not like to multi-byte support as optional.
So, I regret to say that I probably could not do any more about the issue.

Package version freeze (including dependent dependencies) might be a workaround.
